nodeLinker: node-modules

packageExtensions:
  "@ardatan/relay-compiler@12.0.0":
    dependencies:
      "@babel/helper-create-class-features-plugin": 7.25.9
      "@babel/helper-replace-supers": 7.25.9
      "@babel/plugin-proposal-class-properties": 7.18.6
      "@babel/plugin-proposal-object-rest-spread": 7.20.7
      "@babel/plugin-syntax-object-rest-spread": 7.8.3
  "@opentelemetry/api@^1.9.0":
    dependencies:
      "@opentelemetry/core": ^1.9.0
      "@opentelemetry/instrumentation": ^0.54.0
      "@sentry/opentelemetry": ^8.28.0
  "@sentry/nextjs@^8.28.0":
    dependencies:
      "@opentelemetry/api": ^1.9.0
      "@sentry/webpack-plugin": ">=4.40.0"
      webpack: ">=4.40.0"
  "@sentry/opentelemetry@^8.28.0":
    dependencies:
      "@opentelemetry/core": ^1.9.0
      "@opentelemetry/instrumentation": ^0.52.1
      "@opentelemetry/sdk-trace-base": ^1.26.0
      "@opentelemetry/semantic-conventions": ^1.25.1
  "@sentry/react@^8.28.0":
    dependencies:
      react: ^18
  "@sentry/webpack-plugin@8.28.0":
    dependencies:
      "@sentry/cli": ^2.28.0
      "@sentry/utils": ^8.28.0
      webpack: ^5.88.2
