nodeLinker: node-modules
packageExtensions:
  "@sentry/react@^8.28.0":
    dependencies:
      "react": "^18"
  "@opentelemetry/api@^1.9.0":
    dependencies:
      "@opentelemetry/core": "^1.9.0"
      "@opentelemetry/instrumentation": "^0.54.0"
      "@sentry/opentelemetry": "^8.28.0"
  "@sentry/opentelemetry@^8.28.0":
    dependencies:
      "@opentelemetry/core": "^1.9.0"
      "@opentelemetry/sdk-trace-base": "^1.26.0"
      "@opentelemetry/instrumentation": "^0.52.1"
      "@opentelemetry/semantic-conventions": "^1.25.1"
  "@sentry/nextjs@^8.28.0":
    dependencies:
      "@opentelemetry/api": "^1.9.0"
      "webpack": ">=4.40.0"
      "@sentry/webpack-plugin": ">=4.40.0"
  "@sentry/webpack-plugin@8.28.0":
    dependencies:
      "@sentry/cli": "^2.28.0"
      "@sentry/utils": "^8.28.0"
      "webpack": "^5.88.2"
